---
all:
  hosts:
  children:
    archlinux:
      hosts:
      children:
        archlinux_workstations:
          hosts:
          children:
            archlinux_workstations_desktop:
              hosts:
                192.168.1.12:

